// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"

	"com.corexkey/common"
)

// MarshalJSON marshals as JSON.
func (a AccessProfileEntry) MarshalJSON() ([]byte, error) {
	type AccessProfileEntry struct {
		Address     common.Address `json:"address"     gencodec:"required"`
		StorageKeys []common.Hash  `json:"storageKeys" gencodec:"required"`
	}
	var enc AccessProfileEntry
	enc.Address = a.Address
	enc.StorageKeys = a.StorageKeys
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (a *AccessProfileEntry) UnmarshalJSON(input []byte) error {
	type AccessProfileEntry struct {
		Address     *common.Address `json:"address"     gencodec:"required"`
		StorageKeys []common.Hash   `json:"storageKeys" gencodec:"required"`
	}
	var dec AccessProfileEntry
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Address == nil {
		return errors.New("missing required field 'address' for AccessProfileEntry")
	}
	a.Address = *dec.Address
	if dec.StorageKeys == nil {
		return errors.New("missing required field 'storageKeys' for AccessProfileEntry")
	}
	a.StorageKeys = dec.StorageKeys
	return nil
}
