// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package core

import (
	"encoding/json"
	"errors"
	"math/big"

	"com.corexkey/common"
	"com.corexkey/common/hexutil"
	"com.corexkey/common/math"
	"com.corexkey/core/types"
	"com.corexkey/params"
)

var _ = (*genesisSpecMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (g Genesis) MarshalJSON() ([]byte, error) {
	type Genesis struct {
		Config        *params.ChainConfig                        `json:"config"`
		Metadata      *GenesisMetadata                           `json:"corex,omitempty"`
		Nonce         math.HexOrDecimal64                        `json:"nonce"`
		Timestamp     math.HexOrDecimal64                        `json:"timestamp"`
		ExtraData     hexutil.Bytes                              `json:"extraData"`
		GasLimit      math.HexOrDecimal64                        `json:"gasLimit"   gencodec:"required"`
		Difficulty    *math.HexOrDecimal256                      `json:"difficulty" gencodec:"required"`
		Mixhash       common.Hash                                `json:"mixHash"`
		Coinbase      common.Address                             `json:"coinbase"`
		Alloc         map[common.UnprefixedAddress]types.Account `json:"alloc"      gencodec:"required"`
		Number        math.HexOrDecimal64                        `json:"number"`
		GasUsed       math.HexOrDecimal64                        `json:"gasUsed"`
		ParentHash    common.Hash                                `json:"parentHash"`
		BaseFee       *math.HexOrDecimal256                      `json:"baseFeePerGas"`
		ExcessBundleResource *math.HexOrDecimal64                       `json:"excessBundleResource"`
		BundleResourceUsed   *math.HexOrDecimal64                       `json:"bundleResourceUsed"`
	}
	var enc Genesis
	enc.Config = g.Config
	enc.Metadata = g.Metadata
	enc.Nonce = math.HexOrDecimal64(g.Nonce)
	enc.Timestamp = math.HexOrDecimal64(g.Timestamp)
	enc.ExtraData = g.ExtraData
	enc.GasLimit = math.HexOrDecimal64(g.GasLimit)
	enc.Difficulty = (*math.HexOrDecimal256)(g.Difficulty)
	enc.Mixhash = g.Mixhash
	enc.Coinbase = g.Coinbase
	if g.Alloc != nil {
		enc.Alloc = make(map[common.UnprefixedAddress]types.Account, len(g.Alloc))
		for k, v := range g.Alloc {
			enc.Alloc[common.UnprefixedAddress(k)] = v
		}
	}
	enc.Number = math.HexOrDecimal64(g.Number)
	enc.GasUsed = math.HexOrDecimal64(g.GasUsed)
	enc.ParentHash = g.ParentHash
	enc.BaseFee = (*math.HexOrDecimal256)(g.BaseFee)
	enc.ExcessBundleResource = (*math.HexOrDecimal64)(g.ExcessBundleResource)
	enc.BundleResourceUsed = (*math.HexOrDecimal64)(g.BundleResourceUsed)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (g *Genesis) UnmarshalJSON(input []byte) error {
	type Genesis struct {
		Config        *params.ChainConfig                        `json:"config"`
		Metadata      *GenesisMetadata                           `json:"corex,omitempty"`
		Nonce         *math.HexOrDecimal64                       `json:"nonce"`
		Timestamp     *math.HexOrDecimal64                       `json:"timestamp"`
		ExtraData     *hexutil.Bytes                             `json:"extraData"`
		GasLimit      *math.HexOrDecimal64                       `json:"gasLimit"   gencodec:"required"`
		Difficulty    *math.HexOrDecimal256                      `json:"difficulty" gencodec:"required"`
		Mixhash       *common.Hash                               `json:"mixHash"`
		Coinbase      *common.Address                            `json:"coinbase"`
		Alloc         map[common.UnprefixedAddress]types.Account `json:"alloc"      gencodec:"required"`
		Number        *math.HexOrDecimal64                       `json:"number"`
		GasUsed       *math.HexOrDecimal64                       `json:"gasUsed"`
		ParentHash    *common.Hash                               `json:"parentHash"`
		BaseFee       *math.HexOrDecimal256                      `json:"baseFeePerGas"`
		ExcessBundleResource *math.HexOrDecimal64                       `json:"excessBundleResource"`
		BundleResourceUsed   *math.HexOrDecimal64                       `json:"bundleResourceUsed"`
	}
	var dec Genesis
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Config != nil {
		g.Config = dec.Config
	}
	if dec.Metadata != nil {
		g.Metadata = dec.Metadata
	}
	if dec.Nonce != nil {
		g.Nonce = uint64(*dec.Nonce)
	}
	if dec.Timestamp != nil {
		g.Timestamp = uint64(*dec.Timestamp)
	}
	if dec.ExtraData != nil {
		g.ExtraData = *dec.ExtraData
	}
	if dec.GasLimit == nil {
		return errors.New("missing required field 'gasLimit' for Genesis")
	}
	g.GasLimit = uint64(*dec.GasLimit)
	if dec.Difficulty == nil {
		return errors.New("missing required field 'difficulty' for Genesis")
	}
	g.Difficulty = (*big.Int)(dec.Difficulty)
	if dec.Mixhash != nil {
		g.Mixhash = *dec.Mixhash
	}
	if dec.Coinbase != nil {
		g.Coinbase = *dec.Coinbase
	}
	if dec.Alloc == nil {
		return errors.New("missing required field 'alloc' for Genesis")
	}
	g.Alloc = make(types.GenesisAlloc, len(dec.Alloc))
	for k, v := range dec.Alloc {
		g.Alloc[common.Address(k)] = v
	}
	if dec.Number != nil {
		g.Number = uint64(*dec.Number)
	}
	if dec.GasUsed != nil {
		g.GasUsed = uint64(*dec.GasUsed)
	}
	if dec.ParentHash != nil {
		g.ParentHash = *dec.ParentHash
	}
	if dec.BaseFee != nil {
		g.BaseFee = (*big.Int)(dec.BaseFee)
	}
	if dec.ExcessBundleResource != nil {
		g.ExcessBundleResource = (*uint64)(dec.ExcessBundleResource)
	}
	if dec.BundleResourceUsed != nil {
		g.BundleResourceUsed = (*uint64)(dec.BundleResourceUsed)
	}
	return nil
}
